@startuml

WorldObject <-- Creature
WorldObject <-- Item

Item <-- Potion
IUsable <-- Potion

Potion <-- HealingPotion

class WorldObject {
    - {static} maxid : int
    - id : int
    - name : int
    - icon : int

    + getID() : int
    + getName() : string

    'Отображаемая иконка объекта на карте'
    + getIcon() : char
}

class Creature {
    - hp : int
    - maxhp : int
    - attacksList : ArrayList

    + getHP() : int
    + getMaxHP() : int
    + getAttacks() : ArrayList<Attack>
    + attack(target: Creature, attack: Attack)
}

abstract class Item {
    - weight : int
    - size : int

    + getWeight() : int
    + getSize() : int
}

interface IUsable {
    + use()
    + getUseCost() : int
}

interface IMovable {
    'Переместить на определённое количество клеток по x и y'
    + move(x: int, y: int)

    'Переместить в определённую клетку'
    + teleport(x: int, y: int)

    'Может ли объект передвигаться в данный момент'
    + isMovable() : boolean
}

abstract class Potion {
    'Базовая сила действия зелья'
    - value : int

    'Уровень зелья'
    - level : int
}

class HealingPotion {
    + HealingPotion(level: int, value: int, useCost: int)
}

'Нужен ли отдельный интерфейс для поднимаемых объектов?'

@enduml